// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	domain "code-typing-auth-service/internal/core/domain"

	mock "github.com/stretchr/testify/mock"
)

// EventDispatcher is an autogenerated mock type for the EventDispatcher type
type EventDispatcher struct {
	mock.Mock
}

// Dispatch provides a mock function with given fields: event
func (_m *EventDispatcher) Dispatch(event domain.Event) {
	_m.Called(event)
}

// NewEventDispatcher creates a new instance of EventDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventDispatcher {
	mock := &EventDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
