// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ResultsMigrator is an autogenerated mock type for the ResultsMigrator type
type ResultsMigrator struct {
	mock.Mock
}

// MigrateSessionResults provides a mock function with given fields: session, userID
func (_m *ResultsMigrator) MigrateSessionResults(session string, userID string) {
	_m.Called(session, userID)
}

// NewResultsMigrator creates a new instance of ResultsMigrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResultsMigrator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResultsMigrator {
	mock := &ResultsMigrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
